services:
  - type: web
    name: ljudio-server
    runtime: node
    plan: free
    branch: main
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/login
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ljudio-db
          property: connectionString

  - type: web
    name: ljudio-client
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    branch: main
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://ljudio-server.onrender.com

databases:
  - name: ljudio-db
    databaseName: ljudio
    plan: free 