services:
  - type: web
    name: ljudio
    runtime: node
    plan: free
    branch: main
    buildCommand: cd client && rm -rf node_modules package-lock.json && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/login
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ljudio-db
          property: connectionString

databases:
  - name: ljudio-db
    databaseName: ljudio
    plan: free 