services:
  - type: web
    name: ljudio-server
    runtime: node
    plan: free
    branch: main
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/login
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ljudio-db
          property: connectionString

  - type: web
    name: ljudio-client
    runtime: node
    buildCommand: cd client && npm install && npm run build
    startCommand: npx serve -s client/dist
    branch: main
    envVars:
      - key: VITE_API_URL
        value: https://ljudio-server.onrender.com

databases:
  - name: ljudio-db
    databaseName: ljudio
    plan: free 