services:
  - type: web
    name: ljudio
    runtime: node
    plan: free
    branch: main
    buildCommand: |
      cd client && 
      npm install && 
      VITE_API_URL=$RENDER_EXTERNAL_URL npm run build && 
      cd ../server && 
      npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/login
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ljudio-db
          property: connectionString
      - key: RENDER_EXTERNAL_URL
        sync: false

databases:
  - name: ljudio-db
    databaseName: ljudio
    plan: free 